/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Calculator;

import java.util.Scanner;
public class Calculator {
    static Scanner scanner=new Scanner(System.in);
    public static void main(String[] args) {
       
        
    }
}
